// @ts-check

// This runs in Node.js - Don't use client-side code here (browser APIs, JSX...)

/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.

 @type {import('@docusaurus/plugin-content-docs').SidebarsConfig}
 */
const sidebars = {
  // By default, Docusaurus generates a sidebar from the docs folder structure
  main: [
    "home",
    {
      type: 'category',
      label: 'Introduction',
      items: [
        {
          type: 'autogenerated',
          dirName: 'Introduction', // Generate sidebar slice from docs/tutorials/advanced
        },
      ],
    },
    {
      type: 'category',
      label: 'Misc',
      items: [
        {
          type: 'autogenerated',
          dirName: 'Misc', // Generate sidebar slice from docs/tutorials/advanced
        },
      ],
    },
    {
      type: 'autogenerated',
      dirName: 'Faq',
    },
    "codeofconduct",
    "contributing",
    "localisation",
    "license",
  ], 

  bmd: [
    {
      type: 'autogenerated', 
      dirName: "BMD"
    },
  ],
  dev0: [
    {
      type: 'autogenerated', 
      dirName: "Dev0"
    },
  ],
};

export default sidebars;
