name: Automate Dependabot Merges
on:
  pull_request_target:
    types:
      - opened
      - synchronize

permissions:
  pull-requests: write
  contents: write

jobs:
  auto-merge:
    runs-on: ubuntu-latest
    if: github.actor == 'dependabot[bot]'
    steps:
      - name: Check out repository
        uses: actions/checkout@v3

      - name: Fetch Dependabot metadata
        id: metadata
        uses: dependabot/fetch-metadata@v1.3.1
        with:
          github-token: "${{ secrets.GITHUB_TOKEN }}"

      - name: Approve and merge minor and patch updates
        if: |
          steps.metadata.outputs.update-type == 'version-update:semver-minor' || 
          steps.metadata.outputs.update-type == 'version-update:semver-patch'
        run: |
          gh pr review ${{ github.event.pull_request.number }} --approve
          gh pr merge ${{ github.event.pull_request.number }} --merge --auto
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
